plugins { id 'com.android.application' }
android { namespace 'com.virion.absensi'; compileSdk 35
 defaultConfig { applicationId 'com.virion.absensi'; minSdk 23; targetSdk 35; versionCode System.getenv("GITHUB_RUN_NUMBER")?.toInteger() ?: 1; versionName "1.0" }
}
dependencies { implementation 'androidx.core:core-ktx:1.15.0'; implementation 'androidx.appcompat:appcompat:1.7.0'; implementation 'androidx.activity:activity-ktx:1.10.1' }
